# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20160522_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='filtered_image_file',
            field=models.ImageField(null=True, upload_to='static_files/uploaded/filtered/%Y/%m/%d'),
        ),
    ]
