# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20160523_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='discription',
        ),
    ]
